# e2e-audit findings — {{SESSION_ID}}

Generated: {{GENERATED_AT}}
Session dir: `{{SESSION_DIR}}`
Base ref: `{{BASE_REF}}`

## Summary

- Total findings: **{{TOTAL}}**
- Critical / High / Medium / Low / Info: **{{CRIT}} / {{HIGH}} / {{MED}} / {{LOW}} / {{INFO}}**
- Coverage gaps (meta): **{{COVERAGE_GAPS}}**
- Existing specs: **{{SPECS_TOTAL}}** · drift status: **{{DRIFT_STATUS}}**

## Critical + High

{{#each critical_high}}
### {{id}} — {{summary}}

- Rule: `{{rule}}` · Severity: **{{severity}}** · Category: `{{category}}`
- Files: {{files_affected}}
- Assertion: `{{assertion}}`
- Evidence: [screenshot]({{screenshot_path}}) · [trace]({{trace_path}}) · source: `{{source_file}}`
{{#if http}}
- HTTP: `{{http.method}} {{http.path}} → {{http.status}}`
  ```
  {{http.response_snippet}}
  ```
{{/if}}
{{#if detail}}
- Detail: {{detail}}
{{/if}}

{{/each}}

## Coverage gaps

{{#each coverage_gaps}}
### {{id}} — {{summary}}

{{detail}}

Suggested next step: {{#if suggested_fix}}`{{suggested_fix.kind}}` → {{suggested_fix.files}}{{else}}add specs covering the items above{{/if}}

{{/each}}

## Other findings

{{#each others}}
- **{{id}}** [{{severity}}] `{{rule}}` — {{summary}}
{{/each}}

---

_Generated by `e2e-audit` v0.2.0. Verify with `bash .claude/skills/e2e-audit/scripts/verify-audit.sh {{SESSION_DIR}}`._
