# Fix report — `{{session_id}}`

**Date:** {{session_date}}
**Branch:** `{{branch}}`
**Base:** `{{base_sha}}` · **Tip:** `{{tip_sha}}`
**Audit source:** [`findings.json`](../../../.super-design/sessions/{{session_id}}/findings.json)

## Summary

| Status | Count |
|---|---|
| Applied | {{applied}} |
| Proposed (awaiting approval) | {{proposed}} |
| Skipped (HIGH risk → issues) | {{skipped}} |
| Failed (rolled back) | {{failed}} |

---

## Applied fixes — before / after

{{#each applied_findings}}
### {{id}} — {{rule}}{{#if wcag_criterion}} · WCAG {{wcag_criterion}}{{/if}}{{#if nielsen_heuristic}} · Nielsen H{{nielsen_heuristic}}{{/if}}

- **Page:** `{{page_url}}` · **Viewport:** {{viewport}}
- **Severity:** {{severity}}/4 · **Risk:** {{risk_for_fix}} · **Template:** `{{template_id}}`
- **Commit:** [`{{commit_sha_short}}`]({{commit_url}}) — `{{commit_subject}}`
- **Verification:** technical {{technical_result}} · semantic {{semantic_result}}

**Problem**

{{finding}}

**Evidence quote (from audit snapshot):**

```
{{snapshot_quote}}
```

**Before**

Full page:

![before-full F-{{id}}](./screens/{{id}}_before_full.png)

{{#if before_element}}
Element:

![before-element F-{{id}}](./screens/{{id}}_before_element.png)
{{/if}}

**After**

Full page:

![after-full F-{{id}}](./screens/{{id}}_after_full.png)

{{#if after_element}}
Element:

![after-element F-{{id}}](./screens/{{id}}_after_element.png)
{{else if after_element_missing_reason}}
_Element screenshot skipped: {{after_element_missing_reason}}_
{{/if}}

**What changed**

```diff
{{file_diff_summary}}
```

Files touched:
{{#each files_affected}}
- `{{this}}`
{{/each}}

{{#if after_console_errors}}
**Console errors after fix:** {{after_console_errors.length}} — see `fix-results.json` for verbatim.
{{/if}}

---

{{/each}}

{{#if proposed_findings.length}}
## Proposed fixes (awaiting approval)

Before-only evidence is shown because these are not yet applied.

{{#each proposed_findings}}
### {{id}} — {{rule}}

- **Page:** `{{page_url}}` · **Viewport:** {{viewport}}
- **Severity:** {{severity}}/4 · **Risk:** {{risk_for_fix}}
- **Patch:** [`proposals/{{id}}.patch`](../../../.super-design/sessions/{{session_id}}/proposals/{{id}}.patch)

**Problem**

{{finding}}

**Before**

![before F-{{id}}](./screens/{{id}}_before_full.png)

**Proposed change**

```diff
{{proposed_diff}}
```

---

{{/each}}
{{/if}}

{{#if skipped_findings.length}}
## Skipped (HIGH risk — tracked as issues)

{{#each skipped_findings}}
- **{{id}}** · {{rule}} · `{{page_url}}` · Issue [#{{issue_number}}]({{issue_url}}) — {{skip_reason}}
{{/each}}

{{/if}}

{{#if failed_findings.length}}
## Failed (rolled back)

{{#each failed_findings}}
### {{id}} — {{rule}}

- **Failed gate:** {{failed_gate}} ({{gate_reason}})
- **Rolled back:** yes · **Commit sha:** none (reset before commit)

**Before**

![before F-{{id}}](./screens/{{id}}_before_full.png)

**Attempted change (reverted)**

```diff
{{attempted_diff}}
```

---

{{/each}}
{{/if}}

## Reproduce locally

```bash
git switch fix/{{session_id}}
git log --oneline {{base_sha}}..HEAD
git diff {{base_sha}}..HEAD -- <file>
```

Re-run audit to confirm findings cleared:

```bash
# From repo root
super-design --scope <page_url>
```

---

_Generated by `sd-fix` using `fix-report.md.tpl`. Screenshots captured via Playwright MCP at the same viewport as the original audit._
