# Design audit overview — {{project_name}}

> **{{mode_banner}}**
> {{changelog_body}}

## Executive summary

{{executive_summary}}

## Scorecard

| Category | Score | Blockers | High | Medium | Nitpicks |
|---|---|---|---|---|---|
| Nielsen heuristics | {{nielsen_score}}/40 | {{n_blockers_nielsen}} | {{n_high_nielsen}} | {{n_medium_nielsen}} | {{n_nits_nielsen}} |
| WCAG 2.2 AA | {{wcag_score}}% | {{n_blockers_wcag}} | {{n_high_wcag}} | {{n_medium_wcag}} | {{n_nits_wcag}} |
| Core Web Vitals | {{cwv_badge}} | {{n_blockers_cwv}} | {{n_high_cwv}} | — | — |
| Baymard (if applicable) | {{baymard_score}} | {{n_blockers_baymard}} | {{n_high_baymard}} | {{n_medium_baymard}} | — |

## Top findings

### 🚨 Blockers
{{blockers_table}}

### High priority
{{high_table}}

### Medium priority
{{medium_table}}

### Nitpicks
{{nitpicks_table}}

### ✅ Resolved since last audit
{{resolved_table}}

## Market positioning snapshot
{{market_snapshot}}

Full market analysis: `docs/super-design/market-analysis.md`.

## Remediation roadmap
{{roadmap_body}}

## Appendix — evidence
- Per-finding details: `docs/super-design/findings/F-*.md`
- Screenshots: `docs/super-design/.cache/screenshots/`
- axe-core outputs: `docs/super-design/.cache/axe/`
- Web Vitals: `docs/super-design/.cache/vitals/`
- Audit history: `docs/super-design/audit-history.md`

---
*Generated by super-design v{{version}} on {{timestamp}}. Session: `{{session_id}}`.*
