# Research Index

_Auto-generated by `.claude/skills/research/scripts/update-index.sh`. Do not edit by hand._

## Topics

| Topic | Date | Bucket | Status | Confidence | Sources |
|-------|------|--------|--------|------------|---------|
{{#each TOPIC}}
| [{{SLUG}}](./{{SLUG}}.md) | {{DATE}} | {{BUCKET}} | {{FRESHNESS}} | {{CONFIDENCE}} | {{SOURCES_COUNT}} |
{{/each}}

## Decisions (ADRs)

| ADR | Date | Status |
|-----|------|--------|
{{#each ADR}}
| [{{NNNN}}-{{SLUG}}](./decisions/{{NNNN}}-{{SLUG}}.md) | {{DATE}} | {{STATUS}} |
{{/each}}

## Maps of Content

{{#each MOC}}
- [{{TITLE}}](./moc/{{SLUG}}.md)
{{/each}}
