---
title: "{{TITLE}}"
slug: "{{SLUG}}"
date: "{{DATE_YYYY_MM_DD}}"
lang: "{{LANG}}"
content_type_bucket: "{{BUCKET}}"            # fast | medium | slow | permanent
freshness: "{{FRESHNESS}}"                    # fresh | aging | stale | outdated
freshness_window_days: {{WINDOW_DAYS}}
playbook: "{{PLAYBOOK}}"
domain: "{{DOMAIN}}"
sources_count: {{SOURCES_COUNT}}
findings_count: {{FINDINGS_COUNT}}
disagreements_count: {{DISAGREEMENTS_COUNT}}
open_questions_count: {{OPEN_Q_COUNT}}
confidence_summary: "{{CONFIDENCE_SUMMARY}}"  # e.g. "5 high · 3 medium · 1 low"
concepts:
{{CONCEPTS_YAML_LIST}}
session_id: "{{SESSION_ID}}"
---

# Research: {{TITLE}}

> Bucket: **{{BUCKET}}** · Status: **{{FRESHNESS}}** · Confidence: {{CONFIDENCE_SUMMARY}}
> Session: `docs/research/.cache/sessions/{{SESSION_ID}}/`

## Executive summary

{{EXEC_SUMMARY}}

## Question

{{ORIGINAL_QUESTION}}

## Ontology Map

Concepts and their relationships using the SKOS-adapted vocabulary
(see `.claude/skills/research/references/ontology-patterns.md`).

```
{{ONTOLOGY_RELATIONS}}
```

## Findings

{{#each FINDING}}
### Finding {{ID}} — {{TITLE}}

{{ASSERTION}}

**Confidence:** {{CONFIDENCE}}{{#if FRESHNESS_WARNING}} · _Freshness warning: {{FRESHNESS_WARNING}}_{{/if}}{{#if TRIANGULATION_WARNING}} · _Triangulation: {{TRIANGULATION_WARNING}}_{{/if}}

Evidence:

{{#each EVIDENCE}}
> "{{QUOTE}}" [{{SOURCE_ID}}]
> URL: {{URL}}
> Accessed: {{ACCESSED_AT}}
> Verify: {{VERIFY_METHOD}}
{{/each}}

{{/each}}

## Disagreements

{{#each DISAGREEMENT}}
### {{TOPIC}}

- **Position A** ([{{SRC_A}}]): {{POSITION_A}}
- **Position B** ([{{SRC_B}}]): {{POSITION_B}}
- **Resolution requires:** {{RESOLUTION_HINT}}
{{/each}}

## Recommendations

### DO

{{#each RECOMMENDATION_DO}}
- {{TEXT}} — _{{REASON}}_
{{/each}}

### AVOID

{{#each RECOMMENDATION_AVOID}}
- {{TEXT}} — _{{REASON}}_
{{/each}}

## Implementation Path

{{#each STEP}}
{{N}}. {{TEXT}}
{{/each}}

## Open Questions

{{#each OPEN_Q}}
- {{TEXT}}
{{/each}}

## Dead Ends

_Searched but not found / not applicable_

{{#each DEAD_END}}
- {{TEXT}}
{{/each}}

## Sources

| ID | Title | Publisher | Authority (1-5) | Independence | Accessed | URL |
|----|-------|-----------|-----------------|--------------|----------|-----|
{{#each SOURCE}}
| {{ID}} | {{TITLE}} | {{PUBLISHER}} | {{AUTHORITY_LEVEL}} | {{INDEPENDENCE}} | {{ACCESSED_AT}} | {{URL}} |
{{/each}}

---

_Generated by the `research` skill. Pipeline: scout → query → synthesize → verify. Verify status: {{VERIFY_STATUS}}._
