#!/usr/bin/env bash
# update-index.sh — regenerate /docs/research/index.md and per-folder
# indexes from frontmatter of all docs. Idempotent.
set -euo pipefail

ROOT="${CLAUDE_PROJECT_DIR:-$(pwd)}"
DIR="${ROOT}/docs/research"
INDEX="${DIR}/index.md"
DEC_DIR="${DIR}/decisions"
DEC_INDEX="${DEC_DIR}/index.md"
MOC_DIR="${DIR}/moc"
MOC_INDEX="${MOC_DIR}/index.md"

mkdir -p "$DIR" "$DEC_DIR" "$MOC_DIR"

fm_get() {
  # fm_get <file> <key>
  awk -v k="$2" '
    /^---$/ { fm = !fm; next }
    fm {
      if (match($0, "^" k ":")) {
        sub("^" k ":[[:space:]]*", ""); print; exit
      }
    }
  ' "$1"
}

list_topics() {
  find "$DIR" -maxdepth 1 -type f -name "*.md" ! -name "index.md" 2>/dev/null | sort
}

list_decisions() {
  find "$DEC_DIR" -maxdepth 1 -type f -name "*.md" ! -name "index.md" 2>/dev/null | sort
}

list_mocs() {
  find "$MOC_DIR" -maxdepth 1 -type f -name "*.md" ! -name "index.md" 2>/dev/null | sort
}

# ---- root index ----
{
  echo "# Research Index"
  echo
  echo "_Auto-generated by \`.claude/skills/research/scripts/update-index.sh\`. Do not edit by hand._"
  echo
  echo "## Topics"
  echo
  echo "| Topic | Date | Bucket | Status | Confidence | Sources |"
  echo "|-------|------|--------|--------|------------|---------|"
  for f in $(list_topics); do
    SLUG=$(basename "$f" .md)
    DATE=$(fm_get "$f" date); [ -z "$DATE" ] && DATE="—"
    BUCKET=$(fm_get "$f" content_type_bucket); [ -z "$BUCKET" ] && BUCKET="—"
    STATUS=$(fm_get "$f" freshness); [ -z "$STATUS" ] && STATUS="—"
    CONF=$(fm_get "$f" confidence_summary); [ -z "$CONF" ] && CONF="—"
    SRC=$(fm_get "$f" sources_count); [ -z "$SRC" ] && SRC="—"
    echo "| [${SLUG}](./${SLUG}.md) | ${DATE} | ${BUCKET} | ${STATUS} | ${CONF} | ${SRC} |"
  done
  echo
  echo "## Decisions (ADRs)"
  echo
  echo "| ADR | Date | Status |"
  echo "|-----|------|--------|"
  for f in $(list_decisions); do
    SLUG=$(basename "$f" .md)
    DATE=$(fm_get "$f" date); [ -z "$DATE" ] && DATE="—"
    STAT=$(fm_get "$f" status); [ -z "$STAT" ] && STAT="—"
    echo "| [${SLUG}](./decisions/${SLUG}.md) | ${DATE} | ${STAT} |"
  done
  echo
  echo "## Maps of Content"
  echo
  for f in $(list_mocs); do
    SLUG=$(basename "$f" .md)
    echo "- [${SLUG}](./moc/${SLUG}.md)"
  done
} > "$INDEX"

# ---- decisions index ----
{
  echo "# Architecture Decision Records"
  echo
  echo "_Auto-generated. Format: Nygard 2011._"
  echo
  for f in $(list_decisions); do
    SLUG=$(basename "$f" .md)
    DATE=$(fm_get "$f" date); [ -z "$DATE" ] && DATE="—"
    STAT=$(fm_get "$f" status); [ -z "$STAT" ] && STAT="—"
    TITLE=$(fm_get "$f" title); [ -z "$TITLE" ] && TITLE="$SLUG"
    echo "- **[${SLUG}](./${SLUG}.md)** — ${TITLE} _(${DATE} · ${STAT})_"
  done
} > "$DEC_INDEX"

# ---- moc index ----
{
  echo "# Maps of Content"
  echo
  for f in $(list_mocs); do
    SLUG=$(basename "$f" .md)
    echo "- [${SLUG}](./${SLUG}.md)"
  done
} > "$MOC_INDEX"

echo "updated: $INDEX"
echo "updated: $DEC_INDEX"
echo "updated: $MOC_INDEX"
